### ISSUE TITLE
Problem with layout of more than 6 mini buttons

### ISSUE THREAD

**Issue by Pconti31** [csekme/JRibbonMenu#1]
When I try and layout 8 buttons I get this
![limit6-1](https://user-images.githubusercontent.com/44075106/106365264-5b6ebb00-6302-11eb-942f-f50e5f001dda.png)

a small change to line 234 of RibbonBar.java changing
```
					if (slim_count == 3) {
```
to
```
					if (slim_count%3 == 0) {
```
Fixes the problem.
![limit6-2](https://user-images.githubusercontent.com/44075106/106365314-bbfdf800-6302-11eb-86ba-014cf405303b.png)

**Comment by csekme** [comment]
Thanks for the advice. I fixed it.
