### ISSUE TITLE
Can't get tab selection to work

### ISSUE THREAD

**Issue by Pconti31** [csekme/JRibbonMenu#3]
Given two tabs
![tab-1](https://user-images.githubusercontent.com/44075106/106366802-5adb2200-630c-11eb-9f44-d5be730fd434.png)

When I select the second tab "Page Layout" I get this instead
![tab-2](https://user-images.githubusercontent.com/44075106/106366817-70504c00-630c-11eb-9c3d-b96da9fb612d.png)

**Comment by csekme** [comment]
Originally i've thought that the place of residence of this component is border layout at north. I need to figure out how to stay fit in another place. This project was made solution of quick and dirty :( You're the first one who use it besides me. So I'd like to clean it up.
First of all I'd like to correct these issues.

**Comment by Pconti31** [comment]
@csekme I understand quick and dirty (my friends in England call such programs cheap and cheery).
My first open source project started that way and now its evolved into a nice program.
If you check out my repro you can see my current ribbon.
[GUIsliceBuilder](https://github.com/ImpulseAdventure/GUIslice-Builder)
The  current ribbon is part of a third party open source project called insubstantial subproject flamingo.  Its no longer supported and its causing my program to crash and burn on various platforms including Apple's MacOS.

The code is impossible to follow so I thought I would try and write my own.   Then I found yours and its really quite well done and simple to understand. 
So good job!   
It makes a good starting point for me.   Two additional items I plan on adding are Tooltips and action commands.  If you are interest in either of them I'll post a pull request when I'm finished.
Paul--

**Comment by Pconti31** [comment]
@csekme FYI, I have isolated the problem to the toggle function. If I comment out the minimize part my pageLayout tab comes up fine.
Paul--

**Comment by csekme** [comment]
Dear Paul,

I'm so glad that you find it useful. Thanks for your kind words. It's always good to get a positive feedback. 
Yes of course that would be great. I am keen on waiting your additions. 
I will check your project definitely.

Thanks,
Krisz

**Comment by Pconti31** [comment]
@csekme I just issued a pull request to make the fix for this issue.
Paul--

**Comment by csekme** [comment]
I am new in git, I've used subversion before. I have confused a little bit with pull request, but now i think it's okay. It merged successful. :D
