### ISSUE TITLE
Latest jar truncates my first icon on a tab

### ISSUE THREAD

**Issue by Pconti31** [csekme/JRibbonMenu#5]
Building my sample app with the new library causes the first icon to be truncated.  
With the previous jar this is what shows up and its sized correctly.
![tab-1](https://user-images.githubusercontent.com/44075106/106388206-79dcc100-63ab-11eb-8356-4d3066baf9a8.png)

With 1.05 jar i get this
![icon_truncated](https://user-images.githubusercontent.com/44075106/106388228-911bae80-63ab-11eb-8675-ec9e78489504.png)

Note I also lost centering of text now I get "Text Button" instead of 
  Text
Button

If I increase the size of the text field from "Text" to "Text12345" it does a slightly better job sizing but the 'T' is still cut off.
![icon_trun-2](https://user-images.githubusercontent.com/44075106/106388352-1acb7c00-63ac-11eb-80f9-40522b419af0.png)

Ignore the color differences I haven't added my theme support yet to the new library.

**Comment by Pconti31** [comment]
@csekme I just noticed that with your new version I need to add a '\n' to get 
  Text
Button
So I have that part working and if I add three spaces in front and back of text as "   Text   "  it shows up ok though not as nice as originally.
![icon_trun-3](https://user-images.githubusercontent.com/44075106/106388877-73037d80-63ae-11eb-8173-5ed783564ebf.png)

**Comment by csekme** [comment]
![image](https://user-images.githubusercontent.com/28835241/106392404-eda1bc80-63f1-11eb-9ba7-4db66bad956e.png)

I have used a new variable to set margin both side. I have set it to 8 pixel width. It seems in your pictures your margins goes to negative . Originally it should appear correctly.

**Comment by Pconti31** [comment]
@csekme Super! Thank you!
Paul--
